#!/usr/bin/env zsh

# Idea derived from the thread here:
# http://forums.dropbox.com/topic.php?id=5203
# Test for changes from here:
# http://stackoverflow.com/questions/5143795/how-can-i-check-in-a-bash-script-if-my-local-git-repo-has-changes-or-not

if git diff-index --quiet HEAD --; then
    return                                # No local changes, so no-op
fi

git config core.fileMode false
! git diff-index --quiet HEAD --
has_local_changes=$?
if [ $has_local_changes = 0 ]; then
    git stash save
fi
git config core.fileMode true && \
git reset --hard HEAD
if [ $has_local_changes = 0 ]; then
    git stash pop
fi
